### ISSUE TITLE
Shared variables make PCPArchive fail if used twice

### ISSUE THREAD

**Issue by ghost** [mbaldessari/pcpinteractive#1]
Because the variable `pmns` is shared amongst all instances of `PCPArchive`, every archive will appear to have all the metrics from all the previous archives read. This can fail, especially when reading archives from different machines with different metrics. Fix by assigning `self.pmns = {}` in `__init__` instead of using a class variable.

**Comment by mbaldessari** [comment]
Thanks for the report, should be done

**Comment by ghost** [comment]
That was quick, thank you!
